= About

AWS Lambda function that listen for S3 file uploads made by `aws-lambda-sniff`.
When triggered it copies the audio file over SSH to its destination configured by environment variables.
Audio files are placed in `$SSH_DIR/<artist>/<filename>`.

IMPORTANT: On `SSH_HOST` there must be a public key already in place corresponding to `SSH_PRIVATE_KEY`.
Also make sure that `SSH_HOST`, `SSH_PORT`, `SSH_DIR`, etc. are configured correctly.

== Version

include::VERSION[]

== Dependencies

* `python 2.x`
* `paramiko` (doesn't work with `python-3.x`)
* `tagit` (basics `taglib` based tagger)

== Environment Variables

* `WORK_DIR` - the directory path to download temporary files, etc. (e.g. `/tmp`).
* `SSH_PRIVATE_KEY` - an SSH private key file as a string.
* `SSH_USERNAME`
* `SSH_HOST`
* `SSH_PORT`
* `SSH_DIR` - the base directory on the remote host.
* `SSH_COMMAND` - a command that executed over SSH, e.g `nohup bash script.sh '{}' &> out.log &`, where `{}` is place holder which will receive the audio file's name (without extensions).
